name: Docker Image CI

on:
  push:
    branches: [ "main" ]
      - main

jobs:

  build Local Image:

    runs-on: self-hosted

    steps:
      - name: Git Pull
        run: cd /home/ec2-user/continuous-integration && git pull

      - name: Build Docker Image
        run: sudo docker build -t local_image:0.1 /home/ec2-user/continuous-integration/app

      - name: List Docker Images
        run: sudo docker images
      
      - name: Run Docker Container
        run: sudo docker run -d --name local_container -p 9003:9001 local_image:0.1

      - name: List Docker Processes
        run: sudo docker ps
