name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:

  build Local Image:

    runs-on: self-hosted

    steps:
      
      - name: Location Pull
        run:  pwd

      - name: Git Pull
        run:  git pull     

      - name: Build Docker Image
        run: sudo docker build -t ci-node-app:0.2 /home/ec2-user/continuous-integration-/app

      - name: List Docker Images
        run: sudo docker images
      
      - name: Run Docker Container
        run: sudo docker run -d --name ci-node-app-02 -p 9003:9001 ci-node-app:0.2

      - name: List Docker Processes
        run: sudo docker ps
